//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicYearSection
    {
        public AcademicYearSection()
        {
            this.Students = new HashSet<Student>();
        }
    
        public System.Guid SectionID { get; set; }
        public System.Guid AcademicYearID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
