//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicStaff
    {
        public AcademicStaff()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public System.Guid InstructorID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.Guid RoleID { get; set; }
        public System.Guid DepartmentID { get; set; }
    
        public virtual AcademicStaffRole AcademicStaffRole { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
