//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.AcademicStaffs = new HashSet<AcademicStaff>();
            this.AcademicYearSections = new HashSet<AcademicYearSection>();
            this.Courses = new HashSet<Cours>();
            this.Students = new HashSet<Student>();
        }
    
        public System.Guid DepartmentID { get; set; }
        public System.Guid AcademicYearID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AcademicStaff> AcademicStaffs { get; set; }
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual ICollection<AcademicYearSection> AcademicYearSections { get; set; }
        public virtual ICollection<Cours> Courses { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
