//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegeSystemEntities : DbContext
    {
        public CollegeSystemEntities()
            : base("name=CollegeSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AcademicStaff> AcademicStaffs { get; set; }
        public DbSet<AcademicStaffRole> AcademicStaffRoles { get; set; }
        public DbSet<AcademicYear> AcademicYears { get; set; }
        public DbSet<AcademicYearSection> AcademicYearSections { get; set; }
        public DbSet<CourseGrade> CourseGrades { get; set; }
        public DbSet<CourseMaterial> CourseMaterials { get; set; }
        public DbSet<Cours> Courses { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<MaterialType> MaterialTypes { get; set; }
        public DbSet<Semester> Semesters { get; set; }
        public DbSet<StudentCours> StudentCourses { get; set; }
        public DbSet<StudentGrade> StudentGrades { get; set; }
        public DbSet<Student> Students { get; set; }
    }
}
