//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public System.Guid SemesterID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> AcademicYearID { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
