//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentCourses = new HashSet<StudentCours>();
            this.StudentGrades = new HashSet<StudentGrade>();
        }
    
        public System.Guid StudentID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int AdmissionYear { get; set; }
        public int GraduationYear { get; set; }
        public System.Guid CurrentAcademicYearID { get; set; }
        public System.Guid SectionID { get; set; }
        public string SerialID { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual AcademicYearSection AcademicYearSection { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<StudentCours> StudentCourses { get; set; }
        public virtual ICollection<StudentGrade> StudentGrades { get; set; }
    }
}
