//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGrade
    {
        public System.Guid StudentID { get; set; }
        public System.Guid GradeID { get; set; }
        public decimal Mark { get; set; }
        public int Year { get; set; }
    
        public virtual CourseGrade CourseGrade { get; set; }
        public virtual Student Student { get; set; }
    }
}
